### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [GPUOpen-Effects/AOFX#1]
I would like to point out that an identifier like "[`__AMD_AOFX_H__`](https://github.com/GPUOpen-Effects/AOFX/blob/75cb8577445f38a778b44ede46e6c101141784cf/amd_aofx/inc/AMD_AOFX.h#L23)" [does not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by jstewart-amd** [comment]
While double underscore is technically illegal, its use in libraries in commonplace. Still, we will consider changing our include guard naming convention. Thanks for the feedback.

**Comment by elfring** [comment]
Would you like to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

Will it be better to keep this issue open until all affected components will be fixed?

**Comment by jstewart-amd** [comment]
Reopening issue. A version with clean include guards will be committed and pushed shortly.

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/GPUOpen-Effects/AOFX/commit/794987eb249a58012d34ef1da880336d781c96f8#diff-d38a0936983949910d620fc9fc6aaed4L23 "Deletion of a few underscores").
